version: '3.8'
services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=root
    restart: unless-stopped
  azurite:
    build:
        context: .
        dockerfile: ./src/module/infrastructure/services/external/azure/storage/azurite/Dockerfile
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    restart: unless-stopped

volumes:
  mongodb_data: