messages:
  service:
  module:
    application:
      error:
        not_found: The element you search do not exist. Data not found.
        no_filters: Search could not be realized due to lack of search filters.
    domain:
    infrastructure:
responses:
  module:
    application:
      service:
        success:
          alive: Successfully Request. API is Alive.
        error:
          not_found: Data not found
          bad_request: Bad Request
          mapper: Mapping Error
    domain:
    infrastructure:
      persistence:
        success:
          alive: API Successfully Alive
          created: Successfully created new entity.
          read_found: Successfully found results.
          updated: Successfully updated entity.
          delete: Successfully deleted entity.
        errors:
          delete: Error deleting entity. Data not found.
          updated: Error updating entity.
        warnings:
          read_not_found: Results not found.